### ISSUE TITLE
Root permission

### ISSUE THREAD

**Issue by brainwo** [UpdateCommand/update#12]
`yay` advised not to run using `sudo` but other programs requires root permission to update.

Running without `sudo`:
```
$ update
error: you cannot perform this operation unless you are root.
error: you cannot perform this operation unless you are root.
error: you cannot perform this operation unless you are root.
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date^C
```
 Running under `sudo`:
 ```
 $ sudo update
 ...
 ...
 ...
  -> Avoid running yay as root/sudo.
:: Synchronizing package databases...
 core is up to date
 extra
 community is up to date
 multilib is up to date^C
 ```
 
Proposed solution: `update` should check for root permission and call a privilege escalation tool when necessary.

**Comment by joelparkerhenderson** [comment]
Thanks for reporting this. I'm patching now with a check for yay and root:

```
if command -v yay >/dev/null 2>&1; then
    if [ "$(whoami)" != "root" ]; then
        yay -Syu
    fi
fi
```

Generally the `update` command is aiming to be usable without sudo in the command line, and instead using the user's preferred privilege escalation practice/tool/command.

For example, for your use of sudo, you can set your sudoers to enable your normal user account to run privileged commands, without you needing to type `sudo` on the command line.

Here's discussion about how to do that using sudo, for example:

https://unix.stackexchange.com/questions/18830/how-to-run-a-specific-program-as-root-without-a-password-prompt

Does that information get you what you need?

**Comment by brainwo** [comment]
> For example, for your use of sudo, you can set your sudoers to enable your normal user account to run privileged commands, without you needing to type sudo on the command line.

I didn't know about that. That's a helpful information. Thank you.

**Comment by brainwo** [comment]
Closes by https://github.com/UpdateCommand/update/commit/d4b90930f2d9138a4bd7f6e09aeee1e74593a897
