### ISSUE TITLE
Any plans to support Windows?

### ISSUE THREAD

**Issue by Rudxain** [UpdateCommand/update#6]
I didn't find support for `choco` and `winget` package managers. I know a little bit of PowerShell, but I have more experience in MKSH and Bash, so I could contribute but I rarely use PMs and I don't know how `choco` & `winget` work (I only used `winget` ~3 times in my life)

**Comment by Rudxain** [comment]
Nice! I'll do some research about it before contributing. But I'm busy with 2 repos and other things IRL so it'll take a lot of time. It's more likely that someone else is faster than me and opens the PR before me. I think I could help by searching for willing contributors instead

**Comment by joelparkerhenderson** [comment]
I added starter files for choco and scoop, if you want to try them to see if they work OK for you.

**Comment by Rudxain** [comment]
Thanks! I'll test them in some time, I'm currently working on Linux, and my Windows install doesn't have them installed yet
