### ISSUE TITLE
`wget`?

### ISSUE THREAD

**Issue by Rudxain** [UpdateCommand/update#7]
I don't know if it's named using an alias, but I didn't find [Wget](https://en.wikipedia.org/wiki/Wget) here

**Comment by joelparkerhenderson** [comment]
Thanks, I don't understand what you're asking. Can you say more?

**Comment by Rudxain** [comment]
Sorry for the confusion. I meant that there's a PM names Wget, but I didn't find any reference to it within this repo, so I was wondering if it's named in a different way.

I don't know if Wget is worth adding, but it seems like a good idea

**Comment by joelparkerhenderson** [comment]
Is it possible that you're thinking of "winget" which is a Windows package manager, or "wget" which is a typical unix command similar to "curl" for downloading software?

**Comment by Rudxain** [comment]
Good question, some weeks ago I thought they were the same, but they are actually VERY different.

And I mean the unix `wget`, not MS `winget`

**Comment by joelparkerhenderson** [comment]
OK. When you write above "I don't know if Wget is worth adding, but it seems like a good idea"...

Can you explain more about what you're asking?

**Comment by Rudxain** [comment]
"It seems like a good idea" because the program is still used by people today, and it's a popular solution that's built-in on most distros. But it may not be worth supporting because it's not _exactly_ a package manager, just an alternative to `curl` as you and many people have said.

I've read [this answer on AskUbuntu](https://askubuntu.com/a/580816) to get more informed, because (if I remember correctly) I haven't used `wget`, yet, only `curl`

**Comment by joelparkerhenderson** [comment]
I think I understand what you're saying. 

The commands `curl` and `wget` are typically useful for downloading files, and also for doing GET/POST/etc. of data to web servers. The commands are not typically considered package managers.

Package mangers, such as apt for Ubuntu, homebrew for macOS, choco for Windows, etc. are typically useful for tracking package versions, package dependencies, package updates, etc. 

This wikipedia article is a pretty good explanation IMHO: https://en.wikipedia.org/wiki/Package_manager
