### ISSUE TITLE
Errors on Windows

### ISSUE THREAD

**Issue by Rudxain** [UpdateCommand/update#8]
# Intro
This is related to #6, but it's not the same thing, that's why I opened a new Issue for cleaner organization.

# Problems
I was testing it now, and got some problems. I know the scripts are intended to be run by a POSIX-compliant shell, but that may not be so obvious to new users.

`export` doesn't work on PowerShell (that's expected), I had to run:
```ps1
$Env:PATH += ";C:\Users\[USER_NAME]\update\bin"
```
but that's a temporary change (only applies to current shell session), so I had to go to the env-var editor GUI to add the entry.

The command to copy worked perfectly! (because PS has `cp` as an alias for `Copy-Item`). Surprisingly, PS also recognizes `~` as the `HOME` dir.

Trying to run `update --help` delegates control to the Windows "file opener" (IDK how it's called), because PS only sees it as a *plain-text* file, not an executable. Running `cd ~/update/bin; ./update --help` also tries to open as a text file (I also tried adding the `.sh` extension but got the same result). Tried renaming extension to `.ps1` but got an error saying that the file must be digitally signed (this is expected and okay, as per the PS Execution Policy), same story with `update-choco`.

Tried running `update-choco` line-by-line, `set -euf` throws this error:
```
Set-Variable : A parameter cannot be found that matches parameter name 'euf'.
At line:1 char:5
+ set -euf
+     ~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-Variable], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.SetVariableCommand
```

The `if` statement has a syntax error (missing parentheses). Windows has no `/dev/null` path. `choco upgrade all` executed correctly.

It seems the only option is to install WSL with a Linux distro to make use of Bash, but I don't know if WSL has permission to install stuff outside of the VM.

# System info

Output of `$PSVersionTable`
```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

OS: Windows 10 Home 21H1
Build: 19043.1826

**Comment by Rudxain** [comment]
I could open a PR that makes `update-choco` compatible with PS, but then it would be incompatible with POSIX shells.

`update` is harder to fix, because the only options are:
1. Convert to a polyglot (bad for maintainability and debugging)
2. Create a new script specifically for PS (Windows users would have to run a script with a different name, or the same name in a different dir)

**Comment by joelparkerhenderson** [comment]
Great information, thank you.

> Another option would be to create a separate repo

Yes you're right. A separate repo provides the maximum power and flexibility for PowerShell. Calling the repo anything with "Windows" would be confusing IMHO because so many of my peers are using Windows Subsytem for Linux (WSL) which is, as you know, quite different syntax than PowerShell.

Here's the new repo. It's mostly just a copy-paste of existing code, so it will definitely break, and isn't supposed to be ready for production, etc. The new repo is for you to experiment and do any pull requests that you want. Thanks!

https://github.com/UpdateCommand/update-for-powershell

**Comment by Rudxain** [comment]
> Calling the repo anything with "Windows" would be confusing IMHO because so many of my peers are using Windows Subsytem for Linux (WSL)

Also because PS can be installed on other OSes that aren't Windows.

> The new repo is for you to experiment and do any pull requests that you want. Thanks!

Thank you too. I think I can manually "transpile" the subcommand scripts, but the main `update` will be a challenge lol. I'll need to learn more PS syntax and grammar to finish it.

I'll close this issue because it no longer belongs to this repo
